default_roles:
  - system # basic updates and upgrades
  - cargo # install cargo for package installs
  - zsh
  - starship
  - node
  - zellij
  - tmux
  - fzf
git_user_name: "logtomic"
# git_user_email: ""

