# Pulled directly from the url below and edited to fit my needs
# https://github.com/TechDufus/dotfiles/blob/main/main.yml

---
- name: DotFiles Config
  hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: Detect WSL
      ansible.builtin.import_tasks: pre_tasks/detect_wsl.yml
      tags:
        - always

    - name: Is WSL
      ansible.builtin.debug:
        var: ansible_host_environment_is_wsl
      tags:
        - always

    # - name: Confirm Windows PowerShell Execution Policy
    #   ansible.builtin.import_tasks: pre_tasks/powershell_executionpolicy.yml
    #   when: ansible_host_environment_is_wsl
    #   tags:
    #     - always

    # - name: Detect Host User
    #   ansible.builtin.import_tasks: pre_tasks/whoami_wsl.yml
    #   when: ansible_host_environment_is_wsl
    #   tags:
    #     - always

    # - name: Detect Host User
    #   ansible.builtin.import_tasks: pre_tasks/whoami.yml
    #   tags:
    #     - always

  tasks:
    - name: Set roles
      ansible.builtin.set_fact:
        run_roles: "{{ ansible_run_tags != ['all'] and ansible_run_tags or default_roles | difference(exclude_roles | default([])) }}"
      tags:
        - always

    - name: Display roles
      ansible.builtin.debug:
        var: run_roles
      tags:
        - always

    - name: Run roles
      ansible.builtin.include_role:
        apply:
          tags:
            - "{{ roles_item }}"
        name: "{{ roles_item }}"
      loop_control:
        loop_var: roles_item
      with_items: "{{ run_roles }}"
      tags:
        - always

  post_tasks:
    # - name: Source zshrc file
    #   ansible.builtin.import_tasks: post_tasks/source_zshrc.yml
    #   tags:
    #     - always
