---
- name: "Check if Cargo is Installed"
  ansible.builtin.shell: command -v cargo
  register: cargo_exists
  ignore_errors: true

- name: "Download Installer"
  when: cargo_exists is failed
  ansible.builtin.get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: "0755"
    force: "yes"

- name: "Install Rust/Cargo"
  when: cargo_exists is failed
  ansible.builtin.shell: /tmp/sh.rustup.rs -y

- name: "Update"
  when: cargo_exists is success
  ansible.builtin.shell: rustup update
