---
- name: ZSH | Base install
  become: true
  ansible.builtin.package:
    name: zsh
    state: present

- name: ZSH | Install Oh My Zsh
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh
    depth: 1

- name: ZSH | Install zsh-autosuggestions plugin
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    depth: 1

- name: ZSH | Install zsh-completions plugin
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-completions
    dest: ~/.oh-my-zsh/custom/plugins/zsh-completions
    depth: 1

- name: ZSH | Install zsh-syntax-highlighting plugin
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    depth: 1

- name: ZSH | Change user shell to zsh
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh

- name: ZSH | Copy zshrc
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.zshrc"
    src: ".zshrc"
    mode: u=rwx,g=rx,o=rx
