---
- name: Setup fzf
  block:
    - name: FZF | Check for fzf
      ansible.builtin.shell: command -v fzf
      register: fzf_exists
      ignore_errors: true
      changed_when: false

    - name: FZF | Install via APT
      ansible.builtin.apt:
        name: fzf
        state: present
        update_cache: yes
      when: fzf_exists is failed
