---
- name: Setup tmux
  block:
    - name: Check for tmux
      ansible.builtin.shell: command -v tmux
      register: tmux_exists
      ignore_errors: true

    - name: "Install via APT"
      ansible.builtin.apt:
        name: tmux
        state: present
        update_cache: yes
      when: tmux_exists is failed
