---
- name: Setup tmux
  block:
    - name: TMUX | Check for tmux
      ansible.builtin.shell: command -v tmux
      register: tmux_exists
      ignore_errors: true
      changed_when: false

    - name: TMUX | Install via APT
      ansible.builtin.apt:
        name: tmux
        state: present
        update_cache: yes
      when: tmux_exists is failed
