---
- name: "STARSHIP | Check if Starship is Installed"
  ansible.builtin.shell: command -v starship
  register: starship_exists
  ignore_errors: true
  changed_when: false

- name: "STARSHIP | Install Starship via Cargo"
  when: starship_exists is failed
  community.general.cargo:
    name: starship
    state: latest
    locked: true

- name: "STARSHIP | Ensure zshrc File calls Starship"
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/.zshrc"
    line: 'eval "$(starship init zsh)"'
    state: present
    create: true
    insertafter: EOF
    regexp: '^eval "$(starship init zsh)"$'
    validate: "zsh -n %s"

- name: "STARSHIP | Move Starship Config"
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/.config/starship.toml"
    src: "starship.toml"
    mode: u=rwx,g=rx,o=rx
