---
- name: Setup zellij
  block:
    - name: ZELLIJ | Check for zellij
      ansible.builtin.shell: command -v zellij
      register: zellij_exists
      ignore_errors: true
      changed_when: false

    - name: ZELLIJ | Install via Cargo
      when: zellij_exists is failed
      community.general.cargo:
        name: zellij
        state: latest
