---
- name: "Check if Zellij is Installed"
  ansible.builtin.shell: command -v zellij
  register: zellij_exists
  ignore_errors: yes

- name: "Install Zellij via Cargo"
  when: zellij_exists is failed
  community.general.cargo:
    name: zellij
    state: latest
