---
- name: "Zellij | Install zellij via cargo"
  community.general.cargo:
    name: zellij
    state: latest
# - name: "Zellij | Ensure zellij config directory exists"
#   ansible.builtin.file:
#     path: "{{ ansible_user_dir }}/.config/zellij"
#     state: directory
#     mode: u=rwx,g=rx,o=rx
# - name: "Zellij | Copy config"
#   ansible.builtin.copy:
#     dest: "{{ ansible_user_dir }}/.config/zellij/config.yml"
#     src: "config.kdl"
#     mode: u=rwx,g=rx,o=rx
